USE [master]
GO

/****** Object:  Database [SamplesRepository]    Script Date: 22-May-19 17:03:49 ******/
CREATE DATABASE [SamplesRepository]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Samples', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Samples.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Samples_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Samples_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SamplesRepository] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SamplesRepository].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SamplesRepository] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SamplesRepository] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SamplesRepository] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SamplesRepository] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SamplesRepository] SET ARITHABORT OFF 
GO

ALTER DATABASE [SamplesRepository] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SamplesRepository] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SamplesRepository] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SamplesRepository] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SamplesRepository] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SamplesRepository] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SamplesRepository] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SamplesRepository] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SamplesRepository] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SamplesRepository] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SamplesRepository] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SamplesRepository] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SamplesRepository] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SamplesRepository] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SamplesRepository] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SamplesRepository] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SamplesRepository] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SamplesRepository] SET RECOVERY FULL 
GO

ALTER DATABASE [SamplesRepository] SET  MULTI_USER 
GO

ALTER DATABASE [SamplesRepository] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SamplesRepository] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SamplesRepository] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SamplesRepository] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SamplesRepository] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SamplesRepository] SET  READ_WRITE 
GO

